### ISSUE TITLE
JARS Shutdown

### ISSUE THREAD

**Issue by tomlovesgithub** [jac-uk/documentation#20]
# Expected Outcome
Shut down JARS

# Deliverables
- Document steps to load JARS data for querying it (see #26)
- SQL query of lookup data (see #25)
- Excel spreadsheet of lookup data (see #24)
- End the hosting contract with existing hosting company (Business Analyst & Product Owner will instruct hosting company)

**Comment by KateMJAC** [comment]
Assigned to Drie in March WO.
