### ISSUE TITLE
Include data model documentation and version history

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/documentation#23]
We should document the data models we use in Firestore and Realtime database. Consider the following options:
- JSON Schema
- Javascript Class Objects
- Typescript

We should keep a simple log of when we make changes to our data models. For example lets capture the following data:
```
1.35.0 epic/563
Introduced applications.characterInformationV2 to replace applications.characterInformation
```

NOTE: we could break this down into two tasks: a spike for data model; a task to start logging data model changes

**Comment by warrensearle** [comment]
This will be particularly useful when we roll out Character Information changes and JO Handover report as both these pieces of work involve breaking changes to the data model.

**Comment by HalcyonJAC** [comment]
I would like to establish the following:

- Where should the documentation be stored and in what format?
  - Suggestion - You have a documentation repo so I presume it should go in there. If so I will create a HTML page for each document in the Firestore database, showing the document schema in JSON format.
  - Suggestion - I know that Firestore isn't a relational database as such but I think a high-level entity-relationship diagram would still be useful I think and wouldn't take long to put together.
- What is the intended use for the documentation? For reference purposes only?
- Further to the above, if a database schema is to be enforced within the application this raises several questions and possibilities:
  - If a schema is defined in code should a tool be written that enforces it retrospectively, i.e. it loops through all documents in a collection and adds missing fields, etc?
  - A similar tool could be used as part of CI/CD to add a new field to existing documents in a collection during deployment.
    - Note: If this is required I will do some research first to see if some tools are already available for this.

Darrel

**Comment by HalcyonJAC** [comment]
- [ ] High level ER diagram (use app.digrams.net)
- [ ] Description of each entity, i.e. its intended purpose
- [ ] Description of the relationships between entities
