### ISSUE TITLE
Provide excel lookup spreadsheet from JARS

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/documentation#24]
We need to provide a draft version of the excel spreadsheet for review.

Note: There are live exercises on JARS so the data _could_ change between the draft export and when JARS has been shut down.

**Comment by KateMJAC** [comment]
@londonprojects this ticket may be superseded by your current work. If so, please close the ticket.

**Comment by KateMJAC** [comment]
Jeremy is liaising with Matt on this item.
