### ISSUE TITLE
Write query to export JARS lookup spreadsheet

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/documentation#25]
Write a query to return the following data:

```
    candidate name
    exercise name
    exercise id/ref
    application ref
    date
```

Existing JARS interface can be found here: https://jars.judicialappointments.gov.uk

The JARS source files and database dump are stored on google drive

**Comment by joy-ade** [comment]
@warrensearle @tomlovesgithub  After my meeting yesterday with Sharon she confirmed below Field wouldn't be required then l have deleted it from the requirement. 



candidate contact details (email, postal address, phone)

**Comment by warrensearle** [comment]
Awesome, thanks Joy :)

**Comment by joy-ade** [comment]
@warrensearle @Tomlovesgithub I have updated the ticket based on the new requirements from Sharon and Matt. I hope this is clearer and achievable.

**Comment by KateMJAC** [comment]
Jeremy is liaising with Matt on this item.
