### ISSUE TITLE
Enable external suppliers

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/documentation#32]
There are a number of important tasks to help enable external suppliers, and the in-house team, to work productively and safely.

**Firebase**
- [x] Permissions test: set up new supplier and check assigned permissions. Follow-on task being written up by @KateMJAC 
- [x] Remove old/unused projects
- [x] Remove old/unused collections from Staging database

**Github**
- [x] Permissions. Set up new supplier and test assigned permissions
- [x] Remove/archive old repos

**Documentation**
- [x] Intro for new developers
- [x] Document firebase permissions
- [x] Document github permissions

**Comment by warrensearle** [comment]
@KateMJAC the above tasks are all done. Please review the [documentation](https://jac-uk.github.io/documentation) website and then close this ticket when all is ok :)

**Comment by KateMJAC** [comment]
@warrensearle this all looks great. Thank you for completing against the clock.
