### ISSUE TITLE
Proposal for secondary backups

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/documentation#42]
Propose a plan for secondary backups

 - Use another cloud provider?
 - Use another region within GCP?
 - Google Drive?
 - Use JAC/MoJ servers?
 - Use a physical disk/computer located in JAC offices?

**Comment by andrew-isaac** [comment]
Blocked as @andrew-isaac  needs to source AWS account

**Comment by warrensearle** [comment]
@JeremykJAC @andrew-isaac is there a proposal  / proposed plan for this - can I see?
