### ISSUE TITLE
Software Users and Owners

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/documentation#44]
Could we come up with a definite list of all the software and apps we use, and who the owner (or equivalent) is. Andrew Isaac should always be the owner and if we can add more than one, then we add Matt Howley too . 

We had an issue with Sentry where the admin was a leaver from 2 years ago that couldn't be removed/updated and resulted in us loosing access because our payment card expired

**Comment by andrew-isaac** [comment]
@warrensearle  and @tomlovesgithub can u review the document and comment on the document so we can close this off

**Comment by JeremykJAC** [comment]
https://drive.google.com/drive/folders/1R7XF1fecakMDNR7ZIftSlnu0F5NbUwh7

**Comment by warrensearle** [comment]
> @warrensearle and @tomlovesgithub can u review the document and comment on the document so we can close this off

Sure, have added @tomlovesgithub and @warrensearle as assignees so it's on our radar as there are a few more to add in

**Comment by warrensearle** [comment]
I've added a few more and we can keep the sheet updated now it is in a shared location.

@andrew-isaac there are a couple of actions for you. When they're done we can close this ticket

**Comment by warrensearle** [comment]
- [ ] @warrensearle Place a link to the spreadsheet on our documentation site
