### ISSUE TITLE
Design of Tech Calls and Selection Day Prep Webpage

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/documentation#46]
Admins currently complete a selection day tech call via teams for every candidate invited. The teams would like to move this onto word press via the website research project and need designs to see how it would look and feel for a candidate

Attached is the wording, but there is also a need for videos and information from Microsoft on how to download MS Teams and use it.

[https://app.zenhub.com/files/201485031/5a554442-488d-485e-a561-e6bff9edf4fb/download](https://app.zenhub.com/files/201485031/5a554442-488d-485e-a561-e6bff9edf4fb/download)

This is currently some of the information given to candidates - https://judicialappointments.gov.uk/guidance-on-the-application-process-2/selection-day/

This is the YouTube channel which hasn't be updated for a long time - https://www.youtube.com/channel/UCejOzLmdtpIkyy6gp3gLx3A

There was a proposal to record new videos for it and examples of how interviews would run.

**Comment by JeremykJAC** [comment]
https://www.figma.com/file/YWlSW6gFpA6AT4VZwVTVMz/The-alternative-webpage-to-Tech-Call?node-id=0%3A1&t=DRFRYzW3ZKh7NqV3-0
