### ISSUE TITLE
Gov Notify Templates - API Links to Production

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/documentation#48]
Policy and Operational colleagues are reviewing and editing templates on Gov Notify to ensure all content is relevant and up to date. They also want Digital to move the templates used in automated processes (like IAs and Character) to a folder only the Digital Team can access as currently anyone can edit those templates.

The following needs to completed as a first step:

- [x] A List of all templates in Notify used by the platform and where they are located

**Comment by HalcyonJAC** [comment]
@andrew-isaac Here is the list of all templates: https://docs.google.com/spreadsheets/d/1mjLJBPMXkaFFdhPw7QMtZQucfHAeCN9pW_tiip5SkB0/edit?usp=share_link
