### ISSUE TITLE
Update architecture diagrams to reflect recent changes

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/documentation#57]
Our architecture diagrams and related documentation needs updating to take into account new developments on the platform, e.g. separate QT platform!

**Comment by warrensearle** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/documentation/57?planning-poker) with Zenhub @tomlovesgithub @HalcyonJAC @drieJAC

**Comment by drieJAC** [comment]
This could now do with some input from others in terms of anything they've specifically worked on that should go in this document..
Please note that this is only intended as a high level document.
