### ISSUE TITLE
Penetration Test 

### ISSUE THREAD

**Issue by Franceswog** [jac-uk/documentation#67]
## Background
In JAC digital,  it is essential to ensure the security of our digital infrastructure is up to date. Our previous Penetration Test was conducted in 2021, hence a new test is due to take place. This test is crucial for assessing and enhancing our security measures, safeguarding sensitive data, and reducing the risk of cyber threats. We have partnered with MOJ to conduct this test. DPIA and ITHC  will be documented and stored in Share point and payment  to the contractors to carry out the test will be agreed with MOJ.  The test will focus on four key digital sites: Apply, QT, Assessment, and Admin. The results, including any vulnerabilities, will be thoroughly documented, and recommendations for improvement will be provided to enhance our security posture.

## User Story
As the digital team, I would like assurance that our digital platform sites are secure and resilient against cyber threats. 
As the Digital team, I would like to be able to identify and prioritise vulnerabilities in the digital platforms to improve overall security. 
As a user, I want to trust that my personal information (data) is secure and protected from cyber threats. 

## Benefit(s) to user (if not already clear from User story)
Feeling confident in the platform's security practices, knowing personal information is actively protected from cyber threats. 

## Acceptance Criteria
- It's done when the penetration test has been conducted by MoJ (third party) and we have received their documented findings. 

## Ticket champion
Frances

**Comment by Franceswog** [comment]
ITHC Scoping Document is now complete and emailed to BSi for review. The BSi pre-sales experts are currently reviewing the document and thereafter would issue a statement of work to allow us raise a PO.

**Comment by Franceswog** [comment]
I will meet online with Chitti from BSI tomorrow to discuss the submitted ITHC scoping doc . The meeting needs to take place before BSI can raise a proposal for this project. I have also invited Tom to join us as a Developer to answer any technical questions.

**Comment by Franceswog** [comment]
I have made Josh Koh aware of the pen test.  Once the statement of work and necessary info are available , Josh will set up the company as a supplier and afterwards a  purchase Order  will be raised.

**Comment by Franceswog** [comment]
The meeting with Chitti went well. He needed clarification on the URLs used on the platform such as an admin, super admin etc. Tom was present at the meeting to answer technical questions especially around QT, assessors and  super admins. Chitti, would continue to review the ITHC doc and will revert to us by Tuesday next week on cost and timescale. He will have the statement of work ready for us by then.  Chitti advised he would speak to his seniors about putting together a proposal  to run our applications on an annual basis for  3yrs which can be renewed afterwards.

**Comment by Franceswog** [comment]
Chitti shared an update stating, the proposal is going through its  final approval  stage and once approved the proposal will be  emailed to me.

**Comment by Franceswog** [comment]
We have received the proposal from BSI (14th May), which is currently being reviewed by @MattHowley , @nickaddy and Rob, Once approved, the statement of work will be completed and sent to Josh and Owolabi to raise a PO. BSI has advised that the next available date to start the pen test is July 1, 2024. The test is expected to take approximately 4 to 6 weeks to complete.

**Comment by Franceswog** [comment]
In addition to the previous update, we have 20 days from  when the proposal was received, however, this is  not enforced strictly, should we need more time from the procurement / finance team, BSI will be happy to update the proposal if need be. An email has been sent to Josh and Oluwatoyin OwoJori informing them we are now in receipt of the SOW. Rob Aldridge will be catching up with Josh Koh today to discuss finance for the Pen test.

**Comment by Franceswog** [comment]
The Statement of Works (SoW) is ready to be signed and currently with the MOJ commercial team. However, it is on hold due to the purdah period. Oluwatoyin Owojori will contact us once the SoW has been signed. Imran from BSI has been informed and is willing to hold the proposal for us until the end of the month. If we need to extend this period, I will need to inform him so he can seek approval.

**Comment by nickaddy** [comment]
@Franceswog You seem to have made it clear that we are ready to proceed, but can you please underline that we wish to proceed as soon as the pre-election period has passes and MoJ Finance have signed off the spend? It's unlikely that will take place by the end of the month, so I'd suggest that you ask Imran if he can seek approval for an extension, if that is required.

**Comment by Franceswog** [comment]
Imran from BSI has agreed to extend the proposal validation date to the end of July due to the purdah period and until the SoW has been signed and approved.

**Comment by nickaddy** [comment]
@Franceswog @MattHowley I think we should include, if possible, contractor devices in the Pen tests - there is definitely a potential vulnerability there.

**Comment by Franceswog** [comment]
@Nick, how do I include this in the test doc especially as we have come this far  and now in receipt of the SOW?

**Comment by Franceswog** [comment]
@Nick, how do I include this in the test doc especially as we have come this far  and now in receipt of the SOW?

**Comment by nickaddy** [comment]
@Franceswog I don't know how specific the document is. I wouldn't worry about trying to change anything in the document, but let's make a mental note to ask them in the initial meeting.

**Comment by Franceswog** [comment]
Sure..

**Comment by Franceswog** [comment]
Moj is currently putting together the PO  for BSI . The dept. of taxation were copied into the email to confirm  JAC ''VAT Treatment'' . I forwarded the email to Josh Koh to answer the questions on VAT should one arise from Taxation.  I have also provided BSI contact Information to Zahid Hussain from core services, because he asked for the requestor of the ITHC doc.

**Comment by Franceswog** [comment]
I have been in touch with BSI again today to share the PO number . They have now updated their record with both the PO number and SOW, and will be in touch with us to book a date for a run through on how the test will be carried out including their requirements.

**Comment by nickaddy** [comment]
Great news, @Franceswog, excellent work. Pls include myself, Matt and Tom in that initial meeting.

**Comment by Franceswog** [comment]
An Initial call with BSI has now been booked for 13th Sept. See key details below; 
 •	Kick off / Planning Call – 10am on Friday 13th September with Joe Beauchamp 
•	Testing to commence on Monday 23rd September – Thursday 26th September with Joe Beauchamp and Grant McMillan with Reporting after
•	Expected Report Delivery Date – 10th October  ( QA currently scheduled for 3rd October) 
•	Please note, as per the terms and conditions stated in your proposal, cancellation fees will apply if you decide to cancel or reschedule the work within 9 working days of the test start date.

**Comment by Franceswog** [comment]
The test concluded 27th September . We had daily wash calls at the end of each day with Grant and Joe (BSI Testers). They updated us with daily findings which we acted on  to resolve the issues. A detailed report will be  issued to us with the findings by 10th October.

**Comment by Franceswog** [comment]
The report was received 10th October , please see share point for full report.  We have created tickets on Zen hub for the resulting issues, which the Devs have began working on.
