### ISSUE TITLE
Document restoring from back-up process

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/documentation#72]
## Background
As part of the Disaster Planning strand of the 24-25 Digital Roadmap, it has been identified that there are gaps in documentation of a number of important processes; this seems a logical place to start.

## User Story
As the Digital team, I would like to document the restoring from back-up process so that the team have a shared understanding of the process.

## Benefit(s) to user (if not already clear from User story)
Consolidation of processes related to Disaster Recovery strand.

## Feature(s) Description
- [x] Research and document the process of restoring from a back-up
- [x] Share with the Dev team for wider discussion and sign-off
- [x] Save to the [Documentation > Disaster Recovery](https://drive.google.com/drive/folders/10d8TqoZ6eZ3RCh9TnK4ZI4HFIiWIZuFg) folder

## Acceptance Criteria 
It's done when:
- the restore from back-up process is understood and clearly documented
- the documentation has been discussed and signed off by the Dev team

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/documentation/72?planning-poker) with Zenhub @drieJAC @HalcyonJAC @KoWeiJAC @tomlovesgithub @warrensearle

**Comment by HalcyonJAC** [comment]
Note: there is a command we can restore a backup to a target project. Is there any project on Firebase we can test it?

**Comment by nickaddy** [comment]
@HalcyonJAC Can you seek feedback from other devs on this documentation pls? 

Also, the next step will be to actually test the process; is there a way of doing that as close as possible to the real thing?

**Comment by HalcyonJAC** [comment]
@nickaddy, Yes, I have gone through the documentation with Tom and Omar. I have tested the commands to restore data from a backup file. Do you have some scenarios that we need to restore data from backups?

**Comment by HalcyonJAC** [comment]
Note: There will be a follow-up ticket for future disaster recovery planning. Close this ticket for now.
